engines:
  eslint:
    enabled: true
  csslint:
    enabled: true
  nodesecurity:
    enabled: true
  duplication:
    enabled: true
  fixme:
    enabled: true
  markdownlint:
    enabled: true

ratings:
  paths:
  - "*"

exclude_paths:
- "**/*.min.js"
- "**.min.js"
- "**/*.min.css"
- "**.min.css"
