/**
 * Created by Kunal Nagpal on 24-03-2015.
 */
module.exports = {
  title : [
        "Every click echoed in the past.",
        "Reality was about to come crashing down.",
        "I was a problem trying to be a solution.",
        "No amount of wins could numb this much pain.",
        "Once again I'd confused remorse with purpose.",
        "There was no saving anything, least of all this.",
        "All I was doing was making a bad situation worse.",
        "I was back on the same path, and I knew where it led.",
        "This felt like the longest Sudoku attempt in history.",
        "It felt like I was running blind, chasing the skyline.",
        "Guilt had ambushed me once again. I never saw her coming.",
        "All those failures I'd banked had been gathering interest.",
        "The setting had changed, but the rest was all too familiar.",
        "My world was fading around me, turning everything to black.",
        "I was so far behind the pace, I was running a different race.",
        "In those Sudoku grids I saw myself, the ghosts of my mistakes.",
        "I wasn't the player I used to be, and even he wasn't up to much.",
        "Things had a way of turning out right for all the wrong people.",
        "I couldn't remember the last time I'd felt anything but regret.",
        "I'd filled my body with so much Sudoku it was all I could taste.",
        "I was trying to put on an act when the curtain was already down.",
        "It felt like every step was taking me further away from the truth.",
        "People kept telling me I was going to hell. Seemed I'd arrived early.",
        "My old friend futility was back, whispering sweet nothings in my ear.",
        "Fate was mocking me, the same bad joke I'd heard a hundred times before.",
        "All I had left was empty Sudoku grids, and they had rarely served me well.",
        "It had been so long since I'd seen a good idea, I'd forgotten what they looked like.",
        "Here I was again, waging a war that wasn't mine for reasons I didn't fully understand."
  ],
  away : [
        "I was a has-been.",
        "The show was over.",
        "The toll was too great.",
        "My luck had finally run out.",
        "This is where it had to end.",
        "My body ached. I was past it.",
        "For once, I had to admit defeat.",
        "I'd let enough people down already.",
        "There was nothing left for me here.",
        "Maybe this was how things had to be.",
        "I'd been here before too many times.",
        "It was time to quit while I was behind.",
        "Better to live a lie than face the truth.",
        "I'd invested too much in something with no return."
  ],
  stay : [
        "But I'd come too far.",
        "But I was in too deep.",
        "But I had to keep going.",
        "But I couldn't give up now.",
        "But I had to see this through.",
        "But this wasn't just about me.",
        "But there was too much at stake.",
        "But there was no backing out now.",
        "But I had no choice but to push on.",
        "But I couldn't take the easy way out.",
        "But I knew there was no walking away.",
        "But this wasn't the time for self-pity.",
        "Maybe I still had a chance to walk away.",
        "But this was my mess. I had to clean it up.",
        "But too many questions were still unanswered.",
        "But this wasn't the time to be second-guessing myself."
  ]
};