/**
 * Created by Kunal Nagpal on 24-03-2015.
 */
module.exports = {
  title : [
        "Fate was mocking me, the same bad joke I'd heard a hundred times before.",
        "The setting had changed, but the rest was all too familiar.",
        "I couldn't remember the last time I'd felt anything but regret.",
        "All those failures I'd banked had been gathering interest.",
        "It had been so long since I'd seen a good idea, I'd forgotten what they looked like.",
        "This was the longest suicide attempt in history.",
        "In their faces I saw myself, the ghost of my mistakes.",
        "No amount of pills could numb this much pain.",
        "Every click echoed in the past.",
        "I'd filled my body with so much Sudoku it was all I could taste.",
        "People kept telling me I was going to hell. Seemed I'd arrived early.",
        "Guilt had ambushed me once again. I never saw her coming.",
        "It felt like I was running blind, chasing the skyline.",
        "My world was fading around me, turning everything to black.",
        "I wasn't the man I used to be, and even he wasn't up to much.",
        "Here I was again, waging a war that wasn't mine for reasons I didn't fully understand.",
        "Once again I'd confused remorse with purpose.",
        "Things had a way of turning out right for all the wrong people.",
        "All I was doing was making a bad situation worse.",
        "I was a problem trying to be a solution.",
        "I was trying to put on an act when the curtain was already down.",
        "All I had left was emptiness, and that had rarely served me well.",
        "There was no saving anything, least of all this.",
        "I was back on the same path, and I knew where it led.",
        "I was so far behind the pace, I was running a different race.",
        "Reality was about to come crashing down.",
        "It felt like every step was taking me further away from the truth.",
        "My old friend Futility was back, whispering sweet nothings in my ear."
  ],
  away : [
        "This is where it had to end.",
        "It was time to quit while I was behind.",
        "There was nothing left for me here.",
        "My luck had finally run out.",
        "The show was over.",
        "Maybe this was how things had to be.",
        "For once, I had to admit defeat.",
        "The toll was too great.",
        "Better to live a lie than face the truth.",
        "I'd let enough people down already.",
        "I was a has-been.",
        "I'd invested too much in something with no return.",
        "My body ached. I was past it.",
        "I'd been here before too many times."
  ],
  stay : [
        "Maybe I still had a chance to walk away.",
        "But I couldn't give up now.",
        "But I'd come too far.",
        "But this wasn't the time for self-pity.",
        "But there was no backing out now.",
        "But I had to see this through.",
        "But I was in too deep.",
        "But I couldn't take the easy way out.",
        "But this was my mess. I had to clean it up.",
        "But too many questions were still unanswered.",
        "But there was too much at stake.",
        "But I had to keep going.",
        "But I knew there was no walking away.",
        "But this wasn't just about me.",
        "But I had no choice but to push on.",
        "But this wasn't the time to be second-guessing myself."
  ]
};