//Created by Kunal Nagpal <kunagpal@gmail.com> on 23-02-2015.
module.exports = {
        _id : '',
        dob : new Date(),
        num : '',
        hash : '',
        email : '',
        win : 0,
        loss : 0,
        tied : 0,
        played : 0,
        practice : 0,
        h2h : 0,
        solo : 0,
        challenge : 0,
        points : 0,
        ratio : 0.0,
        form : 1,
        streak: 0,
        worst : -1,
        best : Number.MAX_VALUE,
        avg : 0,
        rep : 0,
        xp : 0,
        visit : 0,
        prevType : '',
        prevTime : 0
};
